#pragma once

// Block type identifiers for voxel editor
#define VOXEL_BLOCK_TYPE_PAINT_TEXTURE 0
#define VOXEL_BLOCK_TYPE_SELECT 1
#define VOXEL_BLOCK_TYPE_PLACE 2
#define VOXEL_BLOCK_TYPE_PLACE_SQUARE_SLOPE 3
#define VOXEL_BLOCK_TYPE_PLACE_TRIANGULAR_SLOPE 4
#define VOXEL_BLOCK_TYPE_PLACE_TRIANGULAR_COMPLEMENT 5


