xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucoredu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucoredu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucscriptdu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucscriptdu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\uccompiledu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\uccompiledu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucsharpdu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucsharpdu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucgeometrydu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucgeometrydu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\uc3ddu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\uc3ddu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucnetbasedu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucnetbasedu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucuidu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucuidu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucdevicedu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucdevicedu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucgamebasedu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\DebugU64\ucgamebasedu64.pdb" "Win64\" /y