xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\ucoreu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\ucoreu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\ucscriptu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\ucscriptu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\uccompileu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\uccompileu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\ucsharpu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\ucsharpu64.pdb" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\ucnetbaseu64.dll" "Win64\" /y
xcopy "%MAGICX_SDK%\winexe\bin\PublishU64\ucnetbaseu64.pdb" "Win64\" /y